--<CR>return {
	--<CR>{
		--<CR>"saghen/blink.cmp",
		--<CR>dependencies = { "rafamadriz/friendly-snippets" },
		--<CR>version = "1.*",
		--<CR>config = function()
			--<CR>require("blink.cmp").setup({
				--<CR>keymap = { preset = "default" },
				--<CR>appearance = {
					--<CR>nerd_font_variant = "mono",
				--<CR>},
			--<CR>})
		--<CR>end,
	--<CR>},
--<CR>}
