require("ghug.remap")
require("ghug.set")
require("ghug.lazy")
--require("mason").setup()
--require("mason-lspconfig").setup()
--require("lspconfig").lua_ls.setup({})
--require("lspconfig").ts_ls.setup({})
--require("lspconfig").tailwindcss.setup({})
